export const Majors = [
  'Aeronautical Management Technology',
  'Air and Operations Management',
  'Air Traffic Control',
  'Air Traffic Control Management',
  'Airport Management and Operations',
  'American Sign Language',
  'Animal & Vet Science',
  'Anthropology',
  'Applied Human Physiology',
  'Applied Science',
  'Archaeology',
  'Architecture',
  'Art',
  'Art - Animation',
  'Art - Art Therapy',
  'Art - Arts, Technology & Multimedia',
  'Art - Comedy',
  'Art - Creative Studies',
  'Art - Dance',
  'Art - Design',
  'Art - Digital Media & Design',
  'Art - Fine Arts',
  'Art - Game Design',
  'Art - Graphic Design',
  'Art - History',
  'Art - Illustration',
  'Art - Interior Architecture',
  'Art - Painting',
  'Art - Photography',
  'Art - Playwriting',
  'Art - Screenwriting',
  'Art - Studio',
  'Art - Visual Arts',
  'Art - VPA Commercial and Advertising Art',
  'Art- Photography',
  'Asian Studies',
  'Astronomy',
  'Athletic Training',
  'Audiology, Speech Language Science',
  'Automotive Restoration',
  'Aviation',
  'Aviation Mgmt',
  'Biochemistry',
  'Biology',
  'Biology - Accelerated Dental',
  'Biology - Accelerated Med',
  'Biology - Animal & Vet Science',
  'Biology - Applied Physiology and Health Management',
  'Biology - Behavioral Neuroscience',
  'Biology - Bio Health Sciences',
  'Biology - Bio-Psychology',
  'Biology - Biochemistry & Molecular',
  'Biology - Bioinformatics',
  'Biology - Biological Sciences',
  'Biology - Biology and society',
  'Biology - Biomedical Science',
  'Biology - Cell',
  'Biology - Chemical Biology',
  'Biology - Coastal Environmental Science',
  'Biology - Cognitive Science',
  'Biology - Computational Biology',
  'Biology - Genetics',
  'Biology - Human',
  'Biology - Immunology & Pathogenesis',
  'Biology - Integrative Physiology',
  'Biology - Marine',
  'Biology - Medicine',
  'Biology - Microbiology',
  'Biology - Molecular',
  'Biology - Molecular & Cell Biology',
  'Biology - Neurobiology',
  'Biology - Pharmacology/Toxicology',
  'Biology - Physiology',
  'Biology - Psychobiology',
  'Biology - Statistical Science',
  'Biology - Zoology',
  'Botany',
  'Brain and Behavioral Sciences',
  'Business',
  'Business - Accounting',
  'Business - Accounting/Actuarial Science',
  'Business - Administration',
  'Business - Advertising',
  'Business - Agriculture',
  'Business - Analytics',
  'Business - Apparel & Merchandising',
  'Business - Applied Economics & Management',
  'Business - Arts & Entertainment Management',
  'Business - Auto Industry Management',
  'Business - Commerce',
  'Business - Communications',
  'Business - Comp Sci Combo',
  'Business - Construction Mgmt',
  'Business - E-Commerce',
  'Business - Economics',
  'Business - Entrepreneurship',
  'Business - Fashion & Apparel Merchandising',
  'Business - Finance',
  'Business - Global',
  'Business - Hospitality',
  'Business - Human and Organizational Development',
  'Business - Industrial Relations',
  'Business - Information Systems',
  'Business - International',
  'Business - International Management',
  'Business - Leadership',
  'Business - Management',
  'Business - Management & Economics',
  'Business - Marketing',
  'Business - Music',
  'Business - Pre-Dental',
  'Business - Public Relations',
  'Business - Real Estate',
  'Business - Sport Leadership',
  'Business - Sports Management',
  'Business - Undecided',
  'Chemistry',
  'Child Development',
  'Chinese',
  'Cinema',
  'Classics',
  'Cognitive Science',
  'Collaborative Health & Human Services',
  'College of Liberal Arts',
  'Communication',
  'Communication - Design',
  'Communication - Disorders',
  'Communication - Intercultural',
  'Communication - Media & Culture',
  'Communication - Public Relations',
  'Communication - Sports',
  'Communication - Strategic Communication',
  'Community Health',
  'Community Studies',
  'Comparative Human Development',
  'Comparative Literature',
  'Computer Science',
  'Computer Science - Business',
  'Computer Science - Cyber Security',
  'Computer Science - Game Science',
  'Computer Science - Math and Physical Science',
  'Computer Science - Undecided',
  'Creative Producing',
  'Criminal Justice',
  'Criminology',
  'Critical Race and Ethnic Studies',
  'Dance',
  'Data Science',
  'Design',
  'Design - Design, Innovation, and Society',
  'Design - Industrial',
  'Design - New Media and Digital Design',
  'Development and Sustainability - International Studies',
  'Drama',
  'Ecology',
  'Economics',
  'Economics - Mathematics',
  'Education',
  'Education - Early',
  'Education - Elementary',
  'Education - English',
  'Education - Integrated Educational Studies',
  'Education - Psychology',
  'Education - Secondary',
  'Education - Special',
  'Education - Technology, Engineering, and Design',
  'Education - Undecided',
  'Engineering',
  'Engineering - Aero',
  'Engineering - Architectural',
  'Engineering - Audio',
  'Engineering - Biochemical',
  'Engineering - Bioengineering',
  'Engineering - Biological',
  'Engineering - Biomedical',
  'Engineering - Chemical',
  'Engineering - Civil',
  'Engineering - Civil & Environmental',
  'Engineering - Computer',
  'Engineering - Electrical',
  'Engineering - Electrical & Computer',
  'Engineering - Environmental',
  'Engineering - General Studies',
  'Engineering - Geological',
  'Engineering - Industrial',
  'Engineering - Management Science',
  'Engineering - Marine',
  'Engineering - Materials',
  'Engineering - Mechanical',
  'Engineering - Mechanical and Aerospace',
  'Engineering - Molecular',
  'Engineering - Nuclear',
  'Engineering - Petroleum',
  'Engineering - Robotics',
  'Engineering - Science',
  'Engineering - Technology',
  'Engineering - Undecided',
  'English',
  'English - Creative Writing',
  'English - Dramatic Writing',
  'English - Linguistics',
  'English - Literature',
  'English - with Film',
  'Environmental Science',
  'Environmental Science - Earth and Oceanographic Science',
  'Environmental Science - Natural Resources',
  'Environmental Science - Policy',
  'Environmental Science - Sustainability',
  'Exercise Science',
  'Family Human Services',
  'Fashion Design',
  'Fashion Merchandising',
  'Film',
  'Film - Communications',
  'Film - Media Arts',
  'Film - Media Studies',
  'Film - Production',
  'Film - Television',
  'Film - Television & Digitial Media',
  'Finance',
  'Forensic Science',
  'French',
  'Gallatin School of Individualized Study',
  'Game Development',
  'General Studies',
  'Global Studies',
  'Government',
  'Government - National Security',
  'Government - Peace Studies',
  'Health Science',
  'Health Science - Healthcare management',
  'Health Science - Human Development',
  'Health Science - Management and Policy',
  'Health Science - Medical Technical',
  'Health Science - Medicine Literature and Society',
  'Health Science - Nutrition',
  'Health Science - Promotion and Disease Prevention',
  'Hearing Science',
  'History',
  'History - American',
  'History - Latin American Studies',
  'Homeland Security',
  'Human - Development',
  'Human - Rights',
  'Human - Services',
  'Humanities',
  'Industrial and Labor Relations',
  'Information Science',
  'Interdisciplinary Studies',
  'Interior Design',
  'International Studies',
  'International Studies - Business',
  'International Studies - Communications',
  'International Studies - Development',
  'International Studies - Economics',
  'International Studies - Europe',
  'Italian',
  'Japanese',
  'Journalism',
  'Journalism - Broadcast',
  'Journalism - Broadcast and Digital',
  'Journalism - Design',
  'Journalism - Media Studies',
  'Journalism - Public Relations',
  'Kinesiology',
  'Kinesiology - Athletic Training',
  'Kinesiology - Exercise Physiology',
  'Kinesiology - Exercise Science',
  'Kinesiology - Health and Exercise Science',
  'Kinesiology - Physical Therapy',
  'Kinesiology - Psychosocial',
  'Kinesiology - Sports',
  'Legal Studies',
  'Liberal Studies',
  'Linguistics',
  'LSA Freshman',
  'LSM/Biology',
  'Math',
  'Math - Applied',
  'Math - Applied Math, Engineering and Physics',
  'Math - Financial Actuarial',
  'Math - Mathematical Analysis',
  'Math - Probability/Statistics',
  'Math - Statistics',
  'Media Studies',
  'Meterology',
  'Music',
  'Music - Business',
  'Music - Clive Davis Institute',
  'Music - Composition',
  'Music - Contemporary',
  'Music - Contemporary Urban Pop',
  'Music - Industry',
  'Music - Jazz Studies',
  'Music - Musical Theatre',
  'Music - Performance',
  'Music - Pop',
  'Music - Production',
  'Music - Technology',
  'Music - Vocal',
  'Natural Sciences',
  'Neuroscience',
  'Non-Governmental Organizations and Social Change',
  'Nursing',
  'Occupational Therapy',
  'Oceanography',
  'Organizational Studies',
  'Parks & Rec',
  'Peace and Conflict Studies',
  'Philosophy',
  'Photography',
  'Physical Sciences',
  'Physical Therapy',
  'Physics',
  'Physics - Astrophysics',
  'Physiology',
  'Plan II Honors',
  'Plant Science',
  'Political Science',
  'Political Science - Ethics, Politics & Economics',
  'Political Science - International Affairs',
  'Political Science - International Economics',
  'Political Science - International Politics',
  'Political Science - Leadership',
  'Political Science - Policy',
  'Political Science - Public Policy',
  'Pre - Business',
  'Pre - Communication',
  'Pre - Computer Science',
  'Pre - Dental',
  'Pre - Education',
  'Pre - Engineering',
  'Pre - Health Sciences',
  'Pre - Law',
  'Pre - Med',
  'Pre - Med (Laboratory)',
  'Pre - Nursing',
  'Pre - Occupational Therapy',
  'Pre - Pharmacy',
  'Pre - Physical Sciences',
  'Pre - Physical Therapy',
  'Pre - Physiology',
  'Pre - Publich Health',
  'Pre - Science',
  'Pre - Social Work',
  'Pre - Vet',
  'Product Design',
  'Professional Pilot',
  'Psychology',
  'Psychology - Child',
  'Psychology - Neuroscience',
  'Psychology - Social & Behavioral',
  'Psychology - Social Behavior',
  'Public Health',
  'Public Health - Community Health',
  'Public Policy - Urban & Environmental',
  'Religious Studies',
  'School of Foreign Service',
  'Science - Clinical Laboratory',
  'Science - Co-op',
  'Science - Mathematical &Physical Sciences',
  'Science - Natural Resources Conservation',
  'Science - Technology',
  'Social Justice',
  'Social Justice - Peace, Citizenship, and Social Responsibility',
  'Social Sciences',
  'Social Studies',
  'Social Work',
  'Sociology',
  'Sociology - American Studies',
  'Sociology - Ethics in Society',
  'Sociology - Near Eastern Languages and Civilizations',
  'Spanish',
  'Speech & Hearing Sciences',
  'Speech Pathology',
  'Sports - Management',
  'Sports - Medicine',
  'Technology - Info Mgmt. & Technology',
  'Theater',
  'Theater - Acting',
  'Theater - Comedic Arts',
  'Theater - Design and Production',
  'Theater - Education',
  'Theater - Musical',
  'Theater - Performing arts',
  'Theater - Stage Mgmt',
  'Theology',
  'Translation',
  'Undecided',
  'Undecided - Architecture',
  'Undecided - Arts & Humanities',
  'Undecided - Biological Sciences',
  'Undecided - Business',
  'Undecided - Engineering',
  'Undecided - Fine Arts',
  'Undecided - Health Sciences',
  'Undecided - Humanities',
  'Undecided - Liberal Arts & Sciences',
  'Undecided - Life Sciences',
  'Undecided - Physical Science',
  'Undecided - School of International Service',
  'Undecided - Science',
  'Undecided - Social Sciences',
  'Undecided - STEM',
  'Undecided - Visual/Fine/Performing Arts',
  'Viticulture',
  'Women & Gender Studies',
]
